language: generic
sudo: required
dist: trusty
os:
  - linux
git:
  depth: 100
script:
  - .travis/script.sh 'travis-docker'
notifications:
  email:
    recipients:
      - i38w7i3@yahoo.co.jp
    on_success: always
    on_failure: always
before_install:
  - (umask 0077; openssl enc -aes-256-cbc -d -salt -K "${_DEPLOY_KEY_DECRYPT_KEY}" -iv "${_DEPLOY_KEY_DECRYPT_IV}" -in .ssh/deploy_key.enc.openssl -out ~/.ssh/deploy_key;)
  - unset -v _DEPLOY_KEY_DECRYPT_KEY _DEPLOY_KEY_DECRYPT_IV
